### ISSUE TITLE
Add to Modx Extras provider?

### ISSUE THREAD

**Issue by andrejilderda** [Oetzie/CustomTVs#1]
Hi Oetzie,

I've just installed your CustomTVs package and it seems incredibly useful! Do you consider to add it to the Modx Extra's provider so that it's available in the Package Browser?

If you need help with documentation or anything, do let me know. 👍

**Comment by Oetzie** [comment]
Hi Ajilderda, nice to hear that. I have some other ideas for some other TVs what I will add to the CustomTVs package. 

All of my extras in my Github account are free for use, and when I have some time I will write documentations and stuff for them. After that I will submit them to the MODX extra's provider.

**Comment by andrejilderda** [comment]
Great! Thanks Oetzie.
